name: Daily Book Notification

on:
    schedule:
        - cron: "9 0 * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.11.9"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install selenium beautifulsoup4

            - name: Run crawler
              env:
                  QUERIES: ${{ secrets.QUERIES }}
                  EMAIL_USER: ${{ secrets.EMAIL_USER }}
                  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
                  TO_EMAIL: ${{ secrets.TO_EMAIL }}
              run: |
                  python main.py
