name: Daily Crawler

on:
    schedule:
        - cron: "9 0 * * *"
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install selenium beautifulsoup4

            - name: Run crawler
              if: github.event_name == 'schedule'
              env:
                  QUERIES: ${{ secrets.QUERIES }}
                  EMAIL_USER: ${{ secrets.EMAIL_USER }}
                  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
                  TO_EMAIL: ${{ secrets.TO_EMAIL }}
              run: |
                  python main.py

            - name: Send test email
              if: github.event_name == 'push'
              env:
                  EMAIL_USER: ${{ secrets.EMAIL_USER }}
                  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
                  TO_EMAIL: ${{ secrets.TO_EMAIL }}
              run: |
                  python test_email.py
