name: Daily Crawler

on:
    schedule:
        - cron: "0 0 * * *"
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Book Notification

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install selenium beautifulsoup4

            - name: Run crawler
              if: github.event_name == 'schedule'
              env:
                  QUERIES: ${{ vars.QUERIES }}
                  EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
                  EMAIL_SENDER_PASSWORD: ${{ secrets.EMAIL_SENDER_PASSWORD }}
                  REGISTER: ${{ vars.REGISTER }}
              run: |
                  python src/main.py

            - name: Send test email
              if: github.event_name == 'push'
              env:
                  EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
                  EMAIL_SENDER_PASSWORD: ${{ secrets.EMAIL_SENDER_PASSWORD }}
                  REGISTER: ${{ vars.REGISTER }}
              run: |
                  python src/main.py --test
